export const PROFILE_LIST_REQUEST = 'PROFILE_LIST_REQUEST';
export const PROFILE_LIST_SUCCESS = 'PROFILE_LIST_SUCCESS';
export const PROFILE_LIST_FAIL = 'PROFILE_LIST_FAIL';

export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST';
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS';
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL';

export const PROFILE_SAVE_REQUEST = 'PROFILE_SAVE_REQUEST';
export const PROFILE_SAVE_SUCCESS = 'PROFILE_SAVE_SUCCESS';
export const PROFILE_SAVE_FAIL = 'PROFILE_SAVE_FAIL';

export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAIL = 'PROFILE_DELETE_FAIL';

export const PROFILE_REVIEW_SAVE_REQUEST = 'PROFILE_REVIEW_SAVE_REQUEST';
export const PROFILE_REVIEW_SAVE_SUCCESS = 'PROFILE_REVIEW_SAVE_SUCCESS';
export const PROFILE_REVIEW_SAVE_FAIL = 'PROFILE_REVIEW_SAVE_FAIL';
export const PROFILE_REVIEW_SAVE_RESET = 'PROFILE_REVIEW_SAVE_RESET';
